name: trigger-binder-action
description: trigger-binder-action

inputs:
  binder_launch_url:
    description: URL to launch the virtual lab on the Binder instance.
    required: true

  binder_token:
    description: 'Authentication token for the Binder instance.'
    required: false

runs:
  using: composite
  steps:
    - name: Set environment
      shell: bash
      env:
        INPUT_BINDER_LAUNCH_URL: ${{ inputs.binder_launch_url }}
        INPUT_TOKEN: ${{ inputs.binder_token }}
      # TODO: authentication
      run: |
        bash trigger_binder.sh "${INPUT_BINDER_LAUNCH_URL}"
