name: repo2docker-action
description: repo2docker-action

inputs:
  registry_password:
    description: ghcr.io password, used for caching images
    required: false

runs:
  using: composite
  steps:
    - name: Set environment
      shell: bash
      run: |
        echo "USER_ID=1000" | tee -a $GITHUB_ENV
        echo "NB_USER=jovyan" | tee -a $GITHUB_ENV
        echo "REPO_DIR=/home/jovyan" | tee -a $GITHUB_ENV
        echo "IMAGE_NAME=ghcr.io/$(echo "${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]')" | tee -a $GITHUB_ENV

    - name: Login to registry
      uses: docker/login-action@v3
      if: ${{ inputs.registry_password != '' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.registry_password }}

    - uses: actions/setup-python@v5

    - name: Install repo2docker
      shell: bash
      run: |
        pip install jupyter-repo2docker==2026.4.0

    - name: Build image
      shell: bash
      run: |
        jupyter-repo2docker \
          --no-run \
          --user-id "${USER_ID}" \
          --user-name "${NB_USER}"  \
          ${{ inputs.registry_password != '' && format('--cache-from "{0}"', env.IMAGE_NAME) || '' }} \
          --target-repo-dir "${REPO_DIR}"  \
          --image-name "${IMAGE_NAME}"  \
          --label "repo2docker.repo=https://github.com/${GITHUB_REPOSITORY}" \
          --label "repo2docker.ref=${GITHUB_REF}" \
          "${PWD}"

    # Push the image so that it can be used by jupyter-repo2docker --cache-from
    # on later builds.
    - name: Push image
      if: ${{ inputs.registry_password != '' }}
      shell: bash
      run: |
        docker push ${IMAGE_NAME}

    - name: Run tests
      shell: bash
      run: |
        set -e

        declare -a test_dirs=(
          "binder/tests"
          ".binder/tests"
        )

        for test_dir in "${test_dirs[@]}"; do
          if [ -d "${PWD}/${test_dir}" ]; then
            echo "::group::Run test scripts found in ${test_dir}/"
            # We pass in bash that is run inside the built container, so watch out for quoting.
            docker run -u ${USER_ID} -w ${REPO_DIR} \
                ${IMAGE_NAME} /bin/bash -c '
                tests_dir="'"${test_dir}"'"
                failed=0

                run_test() {
                  cmd="$1"
                  file="$2"
                  echo -e "\nRunning ${file} with ${cmd}"
                  ${cmd} "${file}"
                  ret=$?
                  if [ $ret -ne 0 ]; then
                    echo "::error file=${file}::Test script failed: ${file}"
                  fi
                  return $ret
                }

                while IFS= read -r -d "" test_file; do
                  run_test bash "${test_file}" || failed=1
                done < <(find "${tests_dir}" -iname '\''*.sh'\'' -print0)

                while IFS= read -r -d "" test_file; do
                  run_test python "${test_file}" || failed=1
                done < <(find "${tests_dir}" -iname '\''*.py'\'' -print0)

                while IFS= read -r -d "" test_file; do
                  run_test Rscript "${test_file}" || failed=1
                done < <(find "${tests_dir}" -iname '\''*.R'\'' -print0)

                while IFS= read -r -d "" test_file; do
                  # set the kernel to the one installed by repo2docker based on the
                  # notebook language
                  kernel_language="$(jq -r .metadata.kernelspec.language "${test_file}")"
                  case "$kernel_language" in
                    "python")
                      kernel_name="python3"
                      ;;
                    "R")
                      kernel_name="ir"
                      ;;
                    "julia")
                      # auto-detect julia kernel (julia-x.y)
                      kernel_name="$(jupyter-kernelspec list | grep julia | awk '\''{print $1}'\'')"
                      ;;
                    *)
                      echo "Unsupported language for ${test_file}: ${kernel_language}"
                      exit 1
                      ;;
                  esac
                  run_test "jupyter-execute --kernel_name=${kernel_name}" "${test_file}" || failed=1
                done < <(find "${tests_dir}" -iname '\''*.ipynb'\'' -print0)

                if [ $failed -ne 0 ]; then
                  echo "::error::Some test scripts failed"
                  exit 1
                fi
            '
            echo "::endgroup::"
          fi
        done
