name: Build, test and publish Virtual Lab
on:
  push:
    branches:
      - '**'
  release:
    types: [published]

permissions:
  packages: write
  pull-requests: write

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: NaaVRE/virtual-lab-action@use-naavre-environment-service
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          naavre_build_token: ${{ secrets.NAAVRE_BUILD_TOKEN }}
