name: Build, test and publish Virtual Lab
on:
  push:
  release:

permissions:
  packages: write
  pull-requests: write

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: NaaVRE/virtual-lab-action@main
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
